version: '3.3'

services:
  api:
    build: .
    ports:
      - '5000:5000'

  api-dev:
    build: .
    command: bash
    working_dir: /appdev
    environment:
      FLASK_APP: 'main.py'
      FLASK_ENV: 'development'
    ports:
      - '5000:5000'
    volumes:
      - '.:/appdev'
